# Site settings
title: "My Portfolio"
email: ""
description: "Assignments and projects organized by grade and subject"
baseurl: "" # leave empty if hosted at https://jas0nmc.github.io
url: "https://jas0nmc.github.io"

# Theme
theme: slate

# Build settings
sass:
  style: compressed

plugins:
  - jekyll-feed

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
